### ISSUE TITLE
Automate install with DeployStudio or Munki tools

### ISSUE THREAD

**Issue by LeJeko** [munki/createOSXinstallPkg#10]
I'm using CreateOSXinstallPkg for months to automate the upgrade to OS X 10.10.x with DeployStudio 1.6.16 and 10.10.5 NetBoot set.
Now with 10.11 netBoot set and DeployStudio 1.7.1, the packages created by CreateOSXinstallPkg hang when it start the postflight even with 10.10 or 10.11 packages.
This is the installer log below:

================
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Product archive /var/tmp/DSNetworkRepository/Packages/InstallOSX_10.10.5_14F27.pkg trustLevel=100
Jan 20 16:20:45 mac-w89520wu64b installer[440]: External component packages (1) trustLevel=100 (trust evaluation failed: Error Domain=PKInstallErrorDomain Code=106 "The package “%@” is missing or invalid." UserInfo={NSLocalizedDescription=The package “%@” is missing or invalid., identifier=com.googlecode.munki.installosx.pkg})
Jan 20 16:20:45 mac-w89520wu64b installer[440]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Jan 20 16:20:45 mac-w89520wu64b installer[440]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/tmp/DSNetworkRepository/Packages/InstallOSX_10.10.5_14F27.pkg/
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Set authorization level to root for session
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Administrator authorization granted.
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Will use PK session
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Using authorization level of root for IFPKInstallElement
Jan 20 16:20:45 mac-w89520wu64b installer[440]: Starting installation:
Jan 20 16:20:46 mac-w89520wu64b installer[440]: Configuring volume "Macintosh HD"
Jan 20 16:20:46 mac-w89520wu64b installer[440]: Preparing disk for local booted install.
Jan 20 16:20:46 mac-w89520wu64b installer[440]: Free space on "Macintosh HD": 282.56 GB (282557243392 bytes).
Jan 20 16:20:46 mac-w89520wu64b installer[440]: Create temporary directory "/Volumes/Macintosh HD/Install.4407aznst"
Jan 20 16:20:46 mac-w89520wu64b installer[440]: IFPKInstallElement (1 packages)
Jan 20 16:20:46 mac-w89520wu64b installer[440]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Jan 20 16:20:46 mac-w89520wu64b installer[440]: PackageKit: ----- Begin install -----
Jan 20 16:20:46 mac-w89520wu64b installer[440]: PackageKit: request=PKInstallRequest <1 packages, destination=/Volumes/Macintosh HD>
Jan 20 16:20:46 mac-w89520wu64b installer[440]: PackageKit: packages=(
        "PKJaguarPackage <file://localhost/var/tmp/DSNetworkRepository/Packages/InstallOSX_10.10.5_14F27.pkg/>"
    )
Jan 20 16:20:47 mac-w89520wu64b installer[440]: PackageKit: Will do receipt-based obsoleting for package identifier com.googlecode.munki.installosx.pkg (prefix path=tmp)
Jan 20 16:20:47 mac-w89520wu64b installer[440]: PackageKit: Extracting file://localhost/var/tmp/DSNetworkRepository/Packages/InstallOSX_10.10.5_14F27.pkg/ (destination=/Volumes/Macintosh HD/.PKInstallSandboxManager/2D662639-705F-4280-95C2-BAE610DC5A29.activeSandbox/Root/tmp, uid=0)
Jan 20 16:20:47 mac-w89520wu64b installer[440]: PackageKit: Using system content trashcan path /Volumes/Macintosh HD/.PKInstallSandboxManager/2D662639-705F-4280-95C2-BAE610DC5A29.activeSandbox/Trashes for sandbox /Volumes/Macintosh HD/.PKInstallSandboxManager/2D662639-705F-4280-95C2-BAE610DC5A29.activeSandbox
Jan 20 16:20:47 mac-w89520wu64b installer[440]: PackageKit: Shoving /Volumes/Macintosh HD/.PKInstallSandboxManager/2D662639-705F-4280-95C2-BAE610DC5A29.activeSandbox/Root (1 items) to /Volumes/Macintosh HD
**Jan 20 16:20:47 mac-w89520wu64b installer[440]: PackageKit: Executing script "./postflight" in /var/tmp/DSNetworkRepository/Packages/InstallOSX_10.10.5_14F27.pkg/Contents/Resources**
Jan 20 16:24:28 mac-w89520wu64b installer[440]: Can not connect to /var/run/systemkeychaincheck.socket: No such file or directory

===============

Has you can see, the script is blocked when it start the ./postflight.... and the last error appears 4 minutes after it hang.
No more log in install.log but the DS log continuously shows: "Installer:PHASE:Running packages scripts..." over and over... I've try to let it for hours but it never finish install....

I think this is a DeployStudio issue because the problem had appears in the last version (1.7.1), even with 10.10 package generated by CreateOSXinstallPkg, but have you an idea of what cause this behavior ?

Thanks for your help

Jerome

**Comment by gregneagle** [comment]
This is probably SIP in El Capitan blocking the use of `bless`.

**Comment by gregneagle** [comment]
Closing this issue; we'll track it in issue #13.
