### ISSUE TITLE
Macos Sierra package install fails with read-only mount

### ISSUE THREAD

**Issue by fuzzycheck** [munki/createOSXinstallPkg#15]
Hi,
  I'm creating the package using the Macos Sierra beta package
  When I install it on a 10.11.6 encrypted with FileVault 2, it fails with this error:

Aug 19 19:44:46 ops31 installd[387]: ./postflight: Traceback (most recent call last):
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/Users/admin/Desktop/InstallOSX_10.12_16A293a_custom.pkg/Contents/Resources/postflight", line 1088, in <module>
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     main()
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/Users/admin/Desktop/InstallOSX_10.12_16A293a_custom.pkg/Contents/Resources/postflight", line 1080, in main
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     updateHelperPartitions(installvolumepath, install_data_path)
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/Users/admin/Desktop/InstallOSX_10.12_16A293a_custom.pkg/Contents/Resources/postflight", line 820, in updateHelperPartitions
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     RPSdir = setupHelperPartition(mountpoint, install_data_path)
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/Users/admin/Desktop/InstallOSX_10.12_16A293a_custom.pkg/Contents/Resources/postflight", line 761, in setupHelperPartition
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     shutil.copy(item, helper_root)
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     copyfile(src, dst)
Aug 19 19:44:46 ops31 installd[387]: ./postflight:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
Aug 19 19:44:46 ops31 installd[387]: ./postflight:     with open(dst, 'wb') as fdst:
Aug 19 19:44:46 ops31 installd[387]: ./postflight: IOError: [Errno 1] Operation not permitted: '/private/tmp/PKInstallSandbox.LXLBtN/tmp/tmpsqY788/System/Library/CoreServices/boot.efi'

  some debug print I added in the postinstall:

 Aug 19 19:44:46 ops31 installd[387]: ./postflight: item:  /OS X Install Data/boot.efi
Aug 19 19:44:46 ops31 installd[387]: ./postflight: mountpoint:  /private/tmp/PKInstallSandbox.LXLBtN/tmp/tmpsqY788
Aug 19 19:44:46 ops31 installd[387]: ./postflight: install_data_path:  /OS X Install Data
Aug 19 19:44:46 ops31 installd[387]: ./postflight: helper_root:  /private/tmp/PKInstallSandbox.LXLBtN/tmp/tmpsqY788/System/Library/CoreServices
*** end debug print

   So it fails trying to copy "/OS X Install Data/boot.ef"i to "/private/tmp/PKInstallSandbox.LXLBtN/tmp/tmpsqY788/System/Library/CoreServices"

   When I check the mount point, I find that it is read-only:

$ mount
/dev/disk2s2 on /private/tmp/PKInstallSandbox.0Vpmg1/tmp/tmpbJvxWW/dmg.o50o99 (hfs, local, nodev, nosuid, read-only, noowners, nobrowse)

  Any idea how I can solve this problem? 
  Thanks for your help,
Fuzzycheck

**Comment by fuzzycheck** [comment]
Hi,
 someone answered elsewhere:

-----
Might need to look at this
https://macops.ca/new-adventures-in-automating-os-x-installs-with-startosinstall
 
The issues might be related to more SIP restrictions in 10.12
 
Also look at https://forums.developer.apple.com/message/143685
 
I think we need to use startosinstall and not createOSXinstallPkg
-----

  And yes, I managed to create an working pkg with startosinstall.

  But a previous issue made me believe that createosxinstallpkg would work when upgrading from El Capitan to Sierra.
https://github.com/munki/createOSXinstallPkg/issues/14
  
  So, is it right to say that it cannot work with createOSXinstallPkg?

Thanks for your input
Fuzzycheck

**Comment by gregneagle** [comment]
Yes, SIP interferes with most uses of createOSXinstallPkg when running under 10.11+.
