### ISSUE TITLE
run OsxInstallPkg with SIP enable 

### ISSUE THREAD

**Issue by kevintruong** [munki/createOSXinstallPkg#16]
Hello, 
I'm working on the project to create OSXInstallPKg 
But want to ask expert here that: Have a way to around the context SIP enable. To run the install package in OSX EL Capitan. I do not want to disable SIP. 

Thank

**Comment by gregneagle** [comment]
I'm having trouble understanding what you are asking.

createOSXinstallPkg was recently updated (yesterday!) to better support running under SIP-enabled environments. There are still environments/workflows that SIP will interfere with, however, and there is probably not much that can be done about that.

**Comment by kevintruong** [comment]
oh, sorry about that. 
I missed the update.  Let's me check. 
Thanks very much

**Comment by gregneagle** [comment]
Since this isn't really an issue, I'm going to close this.
