### ISSUE TITLE
createOSXInstallPkg-generated macOS Sierra installer is leaving `OS X Install Data` folder in root level of boot drive

### ISSUE THREAD

**Issue by rtrouton** [munki/createOSXinstallPkg#18]
I've noticed that a couple of macOS Sierra installers generated by createOSXInstallPkg are leaving behind an `OS X Install Data` folder on the root level of the boot drive. 

I've observed this behavior with two separately generated macOS Sierra 10.12.0 build 16A323 installers:

1. When using a stock createOSXInstallPkg-generated macOS Sierra installer with no added packages.
2. When using a createOSXInstallPkg-generated macOS Sierra installer with added packages

Screenshot is attached.

![screen shot 2016-09-23 at 3 05 05 pm](https://cloud.githubusercontent.com/assets/618055/18798608/502a5642-81a1-11e6-8b2c-4e7b9e4317f1.png)

**Comment by Lotusshaney** [comment]
Same here

**Comment by poundbangbash** [comment]
Another data point from me as well.  
1 upgrade to 10.12.0 16a323 with COSXIP has the "OS X Install Data" folder.
2 upgraded to 10.12.0 16a323 from the Mac App Store do not.

**Comment by gregneagle** [comment]
https://github.com/munki/createOSXinstallPkg/commit/679f788ec35ba471cbe24b3467a4619afd7bd050 seems to fix this.

**Comment by poundbangbash** [comment]
Upgraded from 10.11.6 to 10.12 with a pkg created from the latest code.  The lingering install data folder is not on the root drive.  Looks good in that scenario.

**Comment by rtrouton** [comment]
Also tried out that upgrade scenario (10.11.6 -> 10.12.0) and did not see an `OS X Install Data` or `macOS Install Data` directory on the root of the boot drive.

**Comment by gregneagle** [comment]
Closing this issue.
