### ISSUE TITLE
macOS 10.12/10.12.1  hdiutil Issue?

### ISSUE THREAD

**Issue by shawnhonsberger** [munki/createOSXinstallPkg#21]
Hello,

A seemingly new issue. Since I upgraded my Mac to macOS 10.12/10.12.1, it seems that after I run `createOSXInstallPkg` the Install.ESD does not automatically unmount. After running the build (which works great), running it again gives an `hdiutil` error like:

```Examining and verifying source...
Error: "hdiutil: attach failed - Resource busy
" while mounting InstallESD.dmg.
Could not mount diskimage /Applications/Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg```
After I restart this is resolved. Is anyone else experiencing this error?

Thank you for this great tool. Any help would be greatly appreciated.

Shawn

**Comment by gregneagle** [comment]
I just used createosxinstallpkg to create a new custom install pkg for 10.12.1 this morning and did not see this behavior.

**Comment by shawnhonsberger** [comment]
Hi @gregneagle thanks so much for your response. Will it allow you to run another install pkg afterwards? Thanks, Shawn.

**Comment by gregneagle** [comment]
Just did three in a row without issue, and no evidence (via `mount` output) that the dmg is mounted after the run completes.

Maybe you have some A/V software hanging onto the mounted image?

**Comment by arubdesu** [comment]
If this occurred right after the first download(where it auto-launches), or
the app was launched during the login session, it could be because of this
bug:
https://openradar.appspot.com/radar?id=4948404442497024

**Comment by shawnhonsberger** [comment]
Thank you @gregneagle and @arubdesu this seems exactly right, I didn't think of it at the time but it was immediately after download in the same login session the first time this occurred. After looking at the radar, it seems like the exact same issue. I did however experience the same thing this morning after a restart, but I'll look into which other software could be the cause. Thank you all! I'll close this now. Thanks, Shawn.
