### ISSUE TITLE
firmware-updates

### ISSUE THREAD

**Issue by niklasskoldmark** [munki/createOSXinstallPkg#22]
Hi

Will this package run the firmware-updates that the app does?

I don't know if this is the right place to ask questions, if not it would be great if somebody could point me to the correct forum.

Thanks
Niklas

**Comment by gregneagle** [comment]
The package installs whatever packages are in the InstallESD.dmg in the Install macOS/OS X.app.
If there are firmware updates, it should install those as well.
You should, of course, test and verify.
