### ISSUE TITLE
Not enough space to copy all packages to InstallESD.dmg!

### ISSUE THREAD

**Issue by albinoz** [munki/createOSXinstallPkg#23]
I try to add a package to 10.9.5,
why is warning about InstallESD.dmg,
if does not copy anything inside ?

sudo /Users/adam/Desktop/createOSXinstallPkg-master/createOSXinstallPkg --source /Volumes/10.9.5\ Mavericks/Install\ OS\ X\ Mavericks.app --pkg /Users/adam/Desktop/SecUpd2016-004Mavericks.pkg  --output ~/Desktop/
Password:
Examining and verifying source...
----------------------------------------------------------------
InstallESD.dmg: /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg
OS Version: 10.9.5
OS Build: 13F34
----------------------------------------------------------------
Output path: /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg
Additional packages:
----------------------------------------------------------------
SecUpd2016-004Mavericks.pkg
----------------------------------------------------------------
Total additional package size: 362841 Kbytes
----------------------------------------------------------------
Checking available space on /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg...
Not enough space to copy all packages to InstallESD.dmg!
Available space: 112640 KBytes

**Comment by gregneagle** [comment]
https://github.com/munki/createOSXinstallPkg#notes-on-additional-packages

"An additional limitation: the InstallESD.dmg volume has a limited amount of free space. To date, that space has been around 350MB. This is more than enough for some basic configuration/bootstrapping packages. But don't try to add Microsoft Office or iLife or Adobe Photoshop CS6. Not only are they too big to fit in the available space, they all contain pre- and post- scripts that are almost certain to fail in the OS X install environment."

Looks like the available space in the 10.9.5 dmg is 112640 KBytes and you are trying to add a 362841 Kbytes package.

Sorry! You'll have to find another way to apply the security update post install.

**Comment by albinoz** [comment]
This not a answer I hope,
I was hope createOSXinstallPkgcan create bigger InstallESD.dmg if require ;)

Rather I Create Bigger InstallESD.dmg in my Mavericks.app/Contents/SharedSupport/
And this look work.

sudo /Users/adam/Desktop/createOSXinstallPkg-master/createOSXinstallPkg --source /Volumes/10.9.5\ Mavericks/Install\ OS\ X\ Mavericks.app --pkg /Users/adam/Desktop/SecUpd2016-004Mavericks.pkg  --output ~/Desktop/
Password:
Examining and verifying source...
----------------------------------------------------------------
InstallESD.dmg: /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg
OS Version: 10.9.5
OS Build: 13F34
----------------------------------------------------------------
Output path: /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg
Additional packages:
----------------------------------------------------------------
SecUpd2016-004Mavericks.pkg
----------------------------------------------------------------
Total additional package size: 362841 Kbytes
----------------------------------------------------------------
Checking available space on /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg...
Creating package wrapper...
Copying brtool into package resources...
Creating MacOSXInstaller.choiceChanges...
----------------------------------------------------------------
Downloading and adding IncompatibleAppList pkg...
Downloading http://swcdn.apple.com/content/downloads/24/35/031-03120/pze7m9fqqs7q6sxnx2zh6267v9qixhasiv/OSX_10_9_IncompatibleAppList.pkg to /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg/Contents/Resources/OS X Install Data/OSX_10_9_IncompatibleAppList.pkg...
Writing index.sproduct to /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg/Contents/Resources/OS X Install Data/index.sproduct...
----------------------------------------------------------------
Copying InstallESD into package...
Mounting /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg...
Copying additional packages to InstallESD/Packages/:
    Copying flat package /Users/adam/Desktop/SecUpd2016-004Mavericks.pkg
Creating /private/tmp/tmpgHpKan/dmg.ciBP60/Packages/OSInstall.collection
Unmounting /Volumes/10.9.5 Mavericks/Install OS X Mavericks.app/Contents/SharedSupport/InstallESD.dmg...
Creating disk image at /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg/Contents/Resources/InstallESD.dmg...
Préparation du moteur d’imagerie…
Lecture de Protective Master Boot Record (MBR : 0)…
   (CRC32 $7342A8B1 : Protective Master Boot Record (MBR : 0))
Lecture de GPT Header (Primary GPT Header : 1)…
   (CRC32 $FD9F1417 : GPT Header (Primary GPT Header : 1))
Lecture de GPT Partition Data (Primary GPT Table : 2)…
   (CRC32 $AD98F0C4 : GPT Partition Data (Primary GPT Table : 2))
Lecture de  (Apple_Free : 3)…
   (CRC32 $00000000 :  (Apple_Free : 3))
Lecture de EFI System Partition (C12A7328-F81F-11D2-BA4B-00A0C93EC93B : 4)…
....
   (CRC32 $B54B659C : EFI System Partition (C12A7328-F81F-11D2-BA4B-00A0C93EC93B : 4))
Lecture de disk image (Apple_HFS : 5)…
..................................................................................................................................................
   (CRC32 $2E4F0C09 : disk image (Apple_HFS : 5))
Lecture de  (Apple_Free : 6)…
....................................................................................................................................................
   (CRC32 $00000000 :  (Apple_Free : 6))
Lecture de GPT Partition Data (Backup GPT Table : 7)…
....................................................................................................................................................
   (CRC32 $AD98F0C4 : GPT Partition Data (Backup GPT Table : 7))
Lecture de GPT Header (Backup GPT Header : 8)…
.....................................................................................................................................................
   (CRC32 $1874E322 : GPT Header (Backup GPT Header : 8))
Ajout de ressources…
.....................................................................................................................................................
Temps écoulé :  4m 35.560s
Taille du fichier : 5690681101 octets, Somme de contrôle : CRC32 $03A9D2CE
Secteurs traités : 13671915, 11587508 comprimés
Vitesse : 20.5Moctets/s
Compression : 18.7%
created: /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg/Contents/Resources/InstallESD.dmg
----------------------------------------------------------------
Done! Completed package at: /Users/adam/Desktop/InstallOSX_10.9.5_13F34_custom.pkg

**Comment by gregneagle** [comment]
That's great! I have had no need to add large packages as I use Munki to do additional installs after the OS is installed/upgraded.

PRs welcome that create a dmg with more free space...

**Comment by albinoz** [comment]
The way is less download and upgrade possible,
offline full install.

Best regards,
and thanks for all works !
