### ISSUE TITLE
Error : Missing basesystem.dmg in high Sierra.app

### ISSUE THREAD

**Issue by sumitphogat13** [munki/createOSXinstallPkg#29]
Getting the mentioned error when I try to create vanilla OS pkg of High Sierra using the brtool guideline however same method works well with Sierra 10.12.6

basesystem.dmg is not missing in high Sierra.app it is there under shared support folder

**Comment by gregneagle** [comment]
Development has ceased on this tool.  

https://github.com/munki/createOSXinstallPkg/blob/master/README.md#important-note

**Comment by sumitphogat13** [comment]
Any suggestions on any similar method to create .pkg of the OS , it would be helpful and I am kinda stuck on how to proceed

Thanks a lot for all the support.

**Comment by gregneagle** [comment]
No, I have no suggestions. If there was a clear path forward, I would have taken it.

**Comment by sumitphogat13** [comment]
Many Thanks. :)
