### ISSUE TITLE
Missing BaseSystem.dmg, macOS High Sierra 10.13

### ISSUE THREAD

**Issue by RedClawx** [munki/createOSXinstallPkg#30]
When attempting to run createOSXinstallPkg against the installer for macOS High Sierra I am getting the error "Missing BaseSystem.dmg in /Applications/Install macOS High Sierra.app". It looks like Apple has changed the location of BaseSystem.dmg. In 10.12, it was located inside the InstallESD.dmg disk image as a hidden dmg. It was at the root of the mounted disk image. It now appears to have been moved to outside of the InstallESD.dmg disk image.

**Comment by gregneagle** [comment]
This project is no longer in development and I have no plans to update it to work with High Sierra.

**Comment by RedClawx** [comment]
You should note that on the projects homepage.

**Comment by gregneagle** [comment]
Hopefully that is clearer now. It was there, but too many words perhaps. Lots of "why"...
