### ISSUE TITLE
Minor issue relating to trailing slashes

### ISSUE THREAD

**Issue by henri** [munki/createOSXinstallPkg#5]
In the documentation (readme.md) there are no trailing slashes mentioned in usage examples. If a trailing slash is not used on a 10.11 install then the following is reported : "Install OS X El Capitan.app doesn't appear to be an OS X installer application!"

Adding a trailing slash (eg. "--source /Applications/Install OS X El Capitan.app/") will result in perfect operation.

This project is just excellent! Thanks for all the hard work on making it just work so well!

**Comment by gregneagle** [comment]
Trailing slashes are not required. I suspect you are dragging files into a Terminal window from the Finder, which is adding an extra space to the end of the path.

**Comment by gregneagle** [comment]
Example (without trailing slash):
```
% sudo ./createOSXinstallPkg --source /Applications/Install\ OS\ X\ El\ Capitan\ GM\ Candidate.app
Examining and verifying source...
----------------------------------------------------------------
InstallESD.dmg: /Applications/Install OS X El Capitan GM Candidate.app/Contents/SharedSupport/InstallESD.dmg
OS Version: 10.11
OS Build: 15A282b
----------------------------------------------------------------
Output path: /Users/Shared/munki-git/createosxinstallpkg/InstallOSX_10.11_15A282b.pkg
Creating package wrapper...
Creating MacOSXInstaller.choiceChanges...
----------------------------------------------------------------
Downloading and adding IncompatibleAppList pkg...
```

**Comment by henri** [comment]
I think you are right on the money!
